{% set name = "pypyodbc" %}
{% set version = "1.3.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 23d353c67bfcd7cb200074f2788f97969dd8084855e47e548ec6ec08d17d38fb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - unixodbc  # [unix]
  run:
    - python

test:
  imports:
    - pypyodbc

about:
  home: "https://github.com/jiangwen365/pypyodbc"
  license: MIT
  license_family: MIT
  # https://github.com/jiangwen365/pypyodbc/issues/58
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: "PyPyODBC - A Pure Python ODBC module by ctypes"
  doc_url: https://github.com/jiangwen365/pypyodbc/wiki
  dev_url: https://github.com/jiangwen365/pypyodbc

extra:
  recipe-maintainers:
    - nwani
